//! Fixture-driven parity test against the Python reference.
//!
//! Loads `tests/fixtures/chess_parity.json` (generated by
//! `tools/gen_rust_parity_fixtures.py`) and asserts byte-for-byte equality on
//! the encoded tensor, set-equality on legal actions, and exact equality on
//! every termination predicate. One `#[test]` fn per bucket so failures
//! localise; `all_buckets` aggregates.

use std::collections::BTreeMap;
use std::fs;
use std::path::PathBuf;

use alpha_zero_nano::action::action_to_move;
use alpha_zero_nano::encoding::Player;
use alpha_zero_nano::game::{ChessGame, GameState};
use serde::Deserialize;
use shakmaty::{Move, Role};

#[derive(Debug, Deserialize)]
struct Fixture {
    schema_version: u32,
    num_channels: usize,
    action_size: usize,
    board_shape: [usize; 2],
    samples: Vec<Sample>,
    #[serde(default)]
    #[allow(dead_code)]
    python_chess_version: String,
    #[serde(default)]
    #[allow(dead_code)]
    chess_game_source_sha: String,
}

#[derive(Debug, Deserialize)]
struct Sample {
    bucket: String,
    label: String,
    fen: String,
    moves: Option<Vec<String>>,
    player: i32,
    encoded: Vec<f32>,
    legal_actions: Vec<u32>,
    value: f32,
    terminated: bool,
    is_checkmate: bool,
    is_stalemate: bool,
    is_insufficient_material: bool,
    is_seventyfive_moves: bool,
    is_fivefold_repetition: bool,
    promotion_actions: Option<Vec<PromotionAction>>,
}

#[derive(Debug, Deserialize)]
struct PromotionAction {
    uci: String,
    action: u32,
}

fn load() -> Fixture {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join("chess_parity.json");
    let text = fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    let f: Fixture = serde_json::from_str(&text).expect("parse fixture json");
    assert_eq!(f.schema_version, 1, "unexpected schema_version");
    assert_eq!(f.num_channels, 17);
    assert_eq!(f.action_size, 4096);
    assert_eq!(f.board_shape, [8, 8]);
    f
}

fn build_state(s: &Sample) -> GameState {
    if let Some(moves) = &s.moves {
        let mut g = GameState::initial();
        for uci in moves {
            g.push_uci(uci)
                .unwrap_or_else(|e| panic!("{}/{}: push {uci}: {e}", s.bucket, s.label));
        }
        g
    } else {
        GameState::from_fen(&s.fen)
            .unwrap_or_else(|e| panic!("{}/{}: from_fen({}): {e}", s.bucket, s.label, s.fen))
    }
}

fn check_sample(game: &ChessGame, s: &Sample) {
    let state = build_state(s);
    let tag = format!("{}/{} fen={}", s.bucket, s.label, s.fen);
    let player = Player::from_int(s.player);

    // 1. Encoder byte-for-byte.
    let enc = game.encode_state(&state, player);
    assert_eq!(enc.0.len(), s.encoded.len(), "[{tag}] encoded length mismatch");
    if enc.0 != s.encoded {
        // Print up to 10 mismatching cells so the failure points at exactly
        // what the encoder got wrong.
        let mut diffs = Vec::new();
        for (i, (a, b)) in enc.0.iter().zip(s.encoded.iter()).enumerate() {
            if a != b {
                let ch = i / 64;
                let r = (i % 64) / 8;
                let c = i % 8;
                diffs.push(format!("(ch={ch}, r={r}, c={c}) got={a} want={b}"));
                if diffs.len() >= 10 {
                    break;
                }
            }
        }
        panic!("[{tag}] encoder mismatch:\n  {}", diffs.join("\n  "));
    }

    // 2. Legal actions set.
    let got: Vec<u16> = game.valid_moves(&state);
    let got_u32: Vec<u32> = got.iter().map(|&a| a as u32).collect();
    let want: Vec<u32> = s.legal_actions.clone();
    if got_u32 != want {
        let got_set: std::collections::BTreeSet<_> = got_u32.iter().copied().collect();
        let want_set: std::collections::BTreeSet<_> = want.iter().copied().collect();
        let extra: Vec<_> = got_set.difference(&want_set).collect();
        let missing: Vec<_> = want_set.difference(&got_set).collect();
        panic!(
            "[{tag}] legal_actions mismatch — extra: {extra:?}; missing: {missing:?}"
        );
    }

    // 3. Termination.
    let (v, term) = game.value_and_terminated(&state);
    assert_eq!(v, s.value, "[{tag}] value");
    assert_eq!(term, s.terminated, "[{tag}] terminated");
    assert_eq!(state.is_checkmate(), s.is_checkmate, "[{tag}] is_checkmate");
    assert_eq!(state.is_stalemate(), s.is_stalemate, "[{tag}] is_stalemate");
    assert_eq!(
        state.is_insufficient_material(),
        s.is_insufficient_material,
        "[{tag}] is_insufficient_material"
    );
    assert_eq!(
        state.is_seventyfive_moves(),
        s.is_seventyfive_moves,
        "[{tag}] is_seventyfive_moves"
    );
    assert_eq!(
        state.is_fivefold_repetition(),
        s.is_fivefold_repetition,
        "[{tag}] is_fivefold_repetition"
    );

    // 4. Promotion actions (B10 only).
    if let Some(proms) = &s.promotion_actions {
        for entry in proms {
            let m = action_to_move(&state.pos, entry.action as u16)
                .unwrap_or_else(|e| panic!("[{tag}] action_to_move({}): {e}", entry.action));
            match m {
                Move::Normal { promotion, role, .. } => {
                    assert_eq!(role, Role::Pawn, "[{tag}] {} role", entry.uci);
                    assert_eq!(
                        promotion,
                        Some(Role::Queen),
                        "[{tag}] {} promotion",
                        entry.uci
                    );
                }
                other => panic!("[{tag}] {} → {other:?}, want Normal queen-promo", entry.uci),
            }
        }
    }
}

fn run_bucket(bucket: &str) {
    let f = load();
    let game = ChessGame::new();
    let samples: Vec<_> = f.samples.iter().filter(|s| s.bucket == bucket).collect();
    assert!(!samples.is_empty(), "bucket {bucket} has no samples");
    for s in samples {
        check_sample(&game, s);
    }
}

#[test] fn b1_initial_position() { run_bucket("B1"); }
#[test] fn b2_random_midgame() { run_bucket("B2"); }
#[test] fn b3_checkmate() { run_bucket("B3"); }
#[test] fn b4_stalemate() { run_bucket("B4"); }
#[test] fn b5_insufficient_material() { run_bucket("B5"); }
#[test] fn b6_seventyfive_moves() { run_bucket("B6"); }
#[test] fn b7_fivefold_repetition() { run_bucket("B7"); }
#[test] fn b8_castling_subsets() { run_bucket("B8"); }
#[test] fn b9_en_passant() { run_bucket("B9"); }
#[test] fn b10_promotions() { run_bucket("B10"); }
#[test] fn b11_black_to_move() { run_bucket("B11"); }

#[test]
fn all_buckets() {
    let f = load();
    let game = ChessGame::new();
    let mut by_bucket: BTreeMap<&str, usize> = BTreeMap::new();
    for s in &f.samples {
        *by_bucket.entry(s.bucket.as_str()).or_insert(0) += 1;
        check_sample(&game, s);
    }
    // Make sure every bucket B1..B11 is represented (the generator already
    // checks this, but pin it here too so a hand-edited fixture can't slip).
    for i in 1..=11 {
        let key = format!("B{i}");
        assert!(
            by_bucket.contains_key(key.as_str()),
            "bucket {key} missing from fixture"
        );
    }
}
